import Head from "next/head";
import React from "react";
import HomeBanner from "../component/Home_One/Banner";
import GetSchedule from "../component/Home_One/Get _Schedule";
import LogisticsService from "../component/Home_One/Logistics_Services";
import HomeAbout from "../component/Home_One/About";
import OurAdvantage from "../component/Home_One/Our_Advantages";
import MapArea from "../component/Home_One/Map";
import Testimonials from "../component/Home_One/Testimonial";
import PricingTable from "../component/Common/PricingTable";
import Subscribe from "../component/Common/Subscribe";
import BlogHome from "../component/Common/Blog";
import sm from "../sm.json";
import * as prismic from "@prismicio/client";

export default function Home({ home }) {
  return (
    <div>
      <Head>
        <title>Aeronomi-Airlines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/airplane-flight.webp" />
        <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossOrigin="anonymous"
        />
      </Head>
      <div>
        <HomeBanner homeData={home} />
        <GetSchedule getSchData={home} />
        <LogisticsService logData={home} />
        <HomeAbout homeAbout={home} />
        <OurAdvantage ourAdv={home} />
        <MapArea mapArea={home} />
        <Testimonials testi={home} />
        <PricingTable priceData={home} />
        <Subscribe subData={home} />
        <BlogHome blogData={home} />
      </div>
      <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossOrigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossOrigin="anonymous"
      ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossOrigin="anonymous"
      ></script>
    </div>
  );
}

export async function getStaticProps() {
  const client = prismic.createClient(sm.apiEndpoint);
  const home = await client.getByUID("home", "id-is-home");
  return {
    props: {
      home,
    },
  };
}
